### ISSUE TITLE
big integer return -1

### ISSUE THREAD

**Issue by vinpel** [FGrosse/PHPASN1#21] opened 2014-09-24 19:18 UTC
Hello, 
i've found a problem with big number :

```
$int1= new ASN_Integer('27329582247986455021744172946096660569051589561051333490087175127133313409704369258177580117032300463239993069430188108780068522375921597249886196875635840025258877325690136352074442377928793199004608912275282905559887563288327636213273678741723145705319413687612690511917113685687906266196637448477719878688233171348877591039878469329172797804033242737837693698612298959413778391800316619493399655906166823553525901757394365546962768131813370312748053879456690650062862686879658478717150437787160014784003559410568381409235269389437859772386421117258753064748885099584872337063364464241324800715578256068913666258773');

$x=$int1->getBinary();
$res=ASN_Object::fromBinary($x);
var_dump($int1);
var_dump($res);
```

PHPASN1\classes\asn1\universal\ASN_Integer.class.php

calculateContentLength use abs() who doesn't like big number, 
```
$tmpValue =  gmp_strval(gmp_abs($this->value));
```
help, but the resultant byte string is wrong, haven't figured why ...

**Comment by FGrosse** [comment] 2015-02-14 11:47
Ah I just realized this has just not been implemented and is practically a duplicate of #1

**Closed by FGrosse** 2015-02-14 11:47 UTC
Labels: bug
